version: "3.8"

services:
  client:
    build: ./frontend
    container_name: frontendapp_new1
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    depends_on:
      - server

    stdin_open: true
    tty: true

  server:
    build: ./backend
    container_name: backendapp_new1
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules
