export const ACTIVITY_LOAD_REQUEST = "ACTIVITY_LOAD_REQUEST "
export const ACTIVITY_LOAD_SUCCESS = "ACTIVITY_LOAD_SUCCESS"
export const ACTIVITY_LOAD_FAIL= "ACTIVITY_LOAD_FAIL"
export const ACTIVITY_LOAD_RESET = "ACTIVITY_LOAD_RESET"


export const ACTIVITY_DELETE_REQUEST = "ACTIVITY_DELETE_REQUEST "
export const ACTIVITY_DELETE_SUCCESS = "ACTIVITY_DELETE_SUCCESS"
export const ACTIVITY_DELETE_FAIL= "ACTIVITY_DELETE_FAIL"
export const ACTIVITY_DELETE_RESET = "ACTIVITY_DELETE_RESET"


export const ACTIVITY_CREATE_REQUEST = "ACTIVITY_CREATE_REQUEST "
export const ACTIVITY_CREATE_SUCCESS = "ACTIVITY_CREATE_SUCCESS"
export const ACTIVITY_CREATE_FAIL= "ACTIVITY_CREATE_FAIL"





export const NUTRITION_CREATE_REQUEST = "NUTRITION_CREATE_REQUEST "
export const NUTRITION_CREATE_SUCCESS = "NUTRITION_CREATE_SUCCESS"
export const NUTRITION_CREATE_FAIL= "NUTRITION_CREATE_FAIL"





