export const NUTRITION_LOAD_REQUEST = "NUTRITION_LOAD_REQUEST  "
export const NURTITION_LOAD_SUCCESS = "NURTITION_LOAD_SUCCESS"
export const NUTRITION_LOAD_FAIL = "NUTRITION_LOAD_FAIL"
export const NUTRITION_LOAD_RESET = "NUTRITION_LOAD_RESET"
export const SET_NUTRITION = 'SET_NUTRITION';